services:
  app:
    build: .
    command: sh -c "uvicorn main.main:app --reload --port=8080 --host=0.0.0.0"
    ports:
      - "8080:8080"
    volumes:
      - ./arquivos:/app/arquivos
    environment:
      - GENAI_API_KEY=${GENAI_API_KEY}